### ISSUE TITLE
Consider publishing demo apk

### ISSUE THREAD

**Issue by zchrissirhcz** [minivision-ai/Silent-Face-Anti-Spoofing-APK#1]
Hi,

Thanks for sharing this awesome repo.

However, the whole repo is big (about 50M) to be git cloned, and building its APK also cost some time.

If convenient, I suggest release apk in the github release page. 

Thanks.

**Comment by nullian** [comment]
only clone latest commit using --depth 1 can reduce the repo size, and you can scan the QR code in  [https://github.com/minivision-ai/Silent-Face-Anti-Spoofing](url) to get apk file

**Comment by zchrissirhcz** [comment]
OK. Thanks.
