### ISSUE TITLE
libncnn.a是怎么编译来的呢？

### ISSUE THREAD

**Issue by Silencesss** [minivision-ai/Silent-Face-Anti-Spoofing-APK#11]
我想使用Vulkan来测试一下加速效果，但是我按照ncnn-vulkan的编译教程https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-android编译好了之后，替换原来的libncnn.a，会报错：
![image](https://user-images.githubusercontent.com/30385698/108443784-5c0cc880-7294-11eb-8107-0105d94679b0.png)
当不使用vulkan编译之后的库替换libncnn.a时，会报如下错：
![image](https://user-images.githubusercontent.com/30385698/108443960-b017ad00-7294-11eb-8a35-2f45ed432c93.png)
不能识别undefined reference to `ncnn::Extractor::extract(char const*, ncnn::Mat&)'这个取数据的过程，
因此我想请问您的libncnn.a是怎么编译得到的呢？

**Comment by Silencesss** [comment]
还发现在cmakelists里加入openmp时就闪退报错，报和第一张图片一样的错误

**Comment by wdzhong** [comment]
@Silencesss 您好，请问这个问题解决了吗？我也尝试自己编译得到这个libncnn.a，但是遇到了跟你一样的错误。而且libncnn.a有80多MB，比repo里面这个大多了。
