### ISSUE TITLE
Better Accuracy: https://github.com/Nikit333/Face-Anti-Spoofing-Android-iOS

### ISSUE THREAD

**Issue by Rdp1111** [minivision-ai/Silent-Face-Anti-Spoofing-APK#12]
It this APP made by you company?
[Face-Anti-Spoofing-Android-iOS](https://github.com/Nikit333/Face-Anti-Spoofing-Android-iOS)

**Comment by sarandogou** [comment]
> It this APP made by you company?
> [Face-Anti-Spoofing-Android-iOS](https://github.com/Nikit333/Face-Anti-Spoofing-Android-iOS)

You keep posting the same message everywhere, I guess it's your own repo.
The logs show you're using Huawei ML Kit Liveness detector, do you know what's the price after the trial period?
https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/ml-service-billing-0000001051010023
