### ISSUE TITLE
人脸检测和活体检测，可以有个说明文档不？

### ISSUE THREAD

**Issue by xinsuinizhuan** [minivision-ai/Silent-Face-Anti-Spoofing-APK#2]
活体检测是在人脸检测后，截取的人脸区域进行是否是活体，还是怎么检测的？

**Comment by nullian** [comment]
活体检测的输入是原始的全景图以及人脸框 具体的检测方法可以去[https://github.com/minivision-ai/Silent-Face-Anti-Spoofing](url)查看

**Comment by xinsuinizhuan** [comment]
你好，我想问一下，检测活体，比例是多少则认为是活体？我使用图片检测，获取的活体的confidence都是0.998以上？是值越小，则为活体吗？

**Comment by zhuyingSeu** [comment]
用开源apk测试的吗？apk默认阈值是0.89，大于阈值为活体。

**Comment by xinsuinizhuan** [comment]
不是，我使用ncnn加载的活体检测的模型，然后使用输入高清图片，进行的活体检测识别，输出的结果。
