### ISSUE TITLE
安卓端模型的bin文件和param文件是怎么从pytorch模型转化过来的

### ISSUE THREAD

**Issue by sunvina** [minivision-ai/Silent-Face-Anti-Spoofing-APK#3]

**Comment by zhuyingSeu** [comment]
先把pytorch模型转化为caffe模型，然后caffe模型转bin文件和param文件。

**Comment by sunvina** [comment]
是把pytroch模型转换成.onnx文件，在把.onnx文件转成bin文件和param文件吗？有转换文件的代码吗？

**Comment by nullian** [comment]
模型文件使用ncnn转换的 [https://github.com/Tencent/ncnn](url)
