### ISSUE TITLE
活体模型inference归一化问题

### ISSUE THREAD

**Issue by zhanglaplace** [minivision-ai/Silent-Face-Anti-Spoofing-APK#4]
你好，看训练代码中是进行了数据归一化 x / 255 。https://github.com/minivision-ai/Silent-Face-Anti-Spoofing/blob/master/src/data_io/dataset_loader.py#L22。
但是在模型测试的时候，是没有加归一化。(https://github.com/minivision-ai/Silent-Face-Anti-Spoofing-APK/blob/master/engine/src/main/cpp/live/live.cpp#L60~L63)
是否是在pytorch模型转ncnn的时候，进行了特殊的/255的处理？

**Comment by zhuyingSeu** [comment]
训练代码没有归一化，看看trans.ToTensor，里面修改过。

**Comment by zhanglaplace** [comment]
> 训练代码没有归一化，看看trans.ToTensor，里面修改过。

嗯，看了下确实，不归一化是因为有对比实验支持吗，还是有其他依据？

**Comment by zhuyingSeu** [comment]
可以归一化,影响不大.
